//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _Test.ws {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ws.WebServiceDocSoap")]
    public interface WebServiceDocSoap {
        
        // CODEGEN: Generating message contract since the operation CheckOut is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CheckOut", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        _Test.ws.CheckOutResponse CheckOut(_Test.ws.CheckOutRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CheckOut", ReplyAction="*")]
        System.Threading.Tasks.Task<_Test.ws.CheckOutResponse> CheckOutAsync(_Test.ws.CheckOutRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CheckOutRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Xml.XmlElement input;
        
        public CheckOutRequest() {
        }
        
        public CheckOutRequest(System.Xml.XmlElement input) {
            this.input = input;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CheckOutResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string CheckOutResult;
        
        public CheckOutResponse() {
        }
        
        public CheckOutResponse(string CheckOutResult) {
            this.CheckOutResult = CheckOutResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceDocSoapChannel : _Test.ws.WebServiceDocSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceDocSoapClient : System.ServiceModel.ClientBase<_Test.ws.WebServiceDocSoap>, _Test.ws.WebServiceDocSoap {
        
        public WebServiceDocSoapClient() {
        }
        
        public WebServiceDocSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceDocSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceDocSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceDocSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        _Test.ws.CheckOutResponse _Test.ws.WebServiceDocSoap.CheckOut(_Test.ws.CheckOutRequest request) {
            return base.Channel.CheckOut(request);
        }
        
        public string CheckOut(System.Xml.XmlElement input) {
            _Test.ws.CheckOutRequest inValue = new _Test.ws.CheckOutRequest();
            inValue.input = input;
            _Test.ws.CheckOutResponse retVal = ((_Test.ws.WebServiceDocSoap)(this)).CheckOut(inValue);
            return retVal.CheckOutResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<_Test.ws.CheckOutResponse> _Test.ws.WebServiceDocSoap.CheckOutAsync(_Test.ws.CheckOutRequest request) {
            return base.Channel.CheckOutAsync(request);
        }
        
        public System.Threading.Tasks.Task<_Test.ws.CheckOutResponse> CheckOutAsync(System.Xml.XmlElement input) {
            _Test.ws.CheckOutRequest inValue = new _Test.ws.CheckOutRequest();
            inValue.input = input;
            return ((_Test.ws.WebServiceDocSoap)(this)).CheckOutAsync(inValue);
        }
    }
}
